### ISSUE TITLE
Cannot find "data_management.coco_to_yolo" file to import

### ISSUE THREAD

**Issue by DeviAyyagari** [agentmorris/noaa-fish#1]
https://github.com/agentmorris/noaa-fish/blob/6dcc36626ddebb478df759ea4e71f99940316c13/prepare-noaa-fish-data-for-training.py#L12

**Comment by agentmorris** [comment]
I've added a requirements.txt file; the non-obvious imports come from the [MegaDetector repo](https://github.com/agentmorris/MegaDetector), and can be imported via the [MegaDetector package](https://pypi.org/project/megadetector).

That said, I'm like 99% sure you don't want to run any code in this repo.  Most of the functionality in this repo was related to creating the [LILA data set](https://lila.science/datasets/noaa-puget-sound-nearshore-fish) from non-public sources, and there's no reason to run that code if you don't have the source data.  The YOLOv5 training code is slightly more interesting, but basically boils down to invoking the YOLOv5 command line to train with default parameters, so you will probably create more hassle for yourself than you save if you use this repo to do that.

All that said, a requirements.txt has been added, so have at it!

**Comment by DeviAyyagari** [comment]
Thank you, for adding the requirements.txt file and pointing me to the MetaDetector package.

I am looking to train a YOLOv7 model on the LILA data set. I was looking for some quick helper code to set up the train/test folders and create the label txt files in the YOLOv7 format. I am going to take the relevant parts of this script to do that. 

Thank you for adding the requirements file!
